import unittest
from pathlib import Path


class CharacterIntelligenceRenderTests(unittest.TestCase):
    def test_dossier_template_includes_character_intelligence_hook(self):
        template_text = Path("render/dashboard_template.html").read_text(encoding="utf-8")

        self.assertIn('class="info-box char-card-intelligence-shell"', template_text)
        self.assertIn('class="char-card-intelligence-profile"', template_text)

    def test_dossier_js_includes_character_intelligence_builder_and_labels(self):
        html_dashboard_text = Path("render/html_dashboard.py").read_text(encoding="utf-8")
        js_text = Path("render/src/js/features/character_dossier/dossier_view.js").read_text(encoding="utf-8")
        runtime_text = Path("render/script.js").read_text(encoding="utf-8")
        style_css_text = Path("render/style.css").read_text(encoding="utf-8")
        css_text = Path("render/src/css/features/character/dossier.css").read_text(encoding="utf-8")

        self.assertIn('os.path.join(base_dir, "src", "css", "features", "character", "dossier.css")', html_dashboard_text)
        self.assertIn("function buildDossierIntelligencePanel", js_text)
        self.assertIn("function buildDossierOfficerBriefPanel", js_text)
        self.assertIn("function getDossierIdentitySnapshot", js_text)
        self.assertIn("function getDossierMovementSnapshot", js_text)
        self.assertIn("function buildDossierOfficerNotes", js_text)
        self.assertIn("function buildDossierRecognitionItems", js_text)
        self.assertIn("Officer Brief", js_text)
        self.assertIn("Field Readout", js_text)
        self.assertIn("Deterministic notes grounded in roster, movement, and scan data.", js_text)
        self.assertIn("Officer Notes", js_text)
        self.assertIn("Deterministic cues grounded in roster, movement, and scan data.", js_text)
        self.assertIn("Recognition Record", js_text)
        self.assertIn("Awards & Footprint", js_text)
        self.assertIn("Latest dashboard scan:", js_text)
        self.assertIn("Raid-ready main.", js_text)
        self.assertIn("Level 70 but below raid-ready threshold.", js_text)
        self.assertIn("Missing item-level data; inspect profile source before roster decisions.", js_text)
        self.assertIn("Recently joined; review rank/spec when available.", js_text)
        self.assertIn("Recently rejoined; verify current rank and spec.", js_text)
        self.assertIn("Roster status is stable.", js_text)
        self.assertIn("HKs", js_text)
        self.assertIn("Level 70", js_text)
        self.assertIn("Raid ready", js_text)
        self.assertIn("Staging for raid", js_text)
        self.assertIn("Needs gear", js_text)
        self.assertIn("Still advancing", js_text)
        self.assertNotIn("char-card-officer-badge", js_text)
        self.assertNotIn("Active PvP contributor.", js_text)
        self.assertNotIn("badge.setAttribute('data-tone', tone);", js_text)
        self.assertIn(".char-card-officer-layout", css_text)
        self.assertIn(".char-card-portrait {\n  width: min(100%, 160px);", css_text)
        self.assertIn("max-width: 120px;", css_text)
        self.assertIn(".char-card-header-badges {\n  width: 100%;", css_text)
        self.assertIn(".char-card-officer-footer", css_text)
        self.assertIn(".char-card {", css_text)
        self.assertIn("body[data-route-family=\"character\"]::before {", css_text)
        self.assertIn("body[data-route-family=\"character\"] .char-card {", css_text)
        self.assertIn(".char-card-gear-shell .empty-slot {", css_text)
        self.assertIn(".char-card-gear-shell .empty-slot .empty-slot-text {", css_text)
        self.assertIn(".char-card-gear-shell .empty-slot .gear-slot-quality {", css_text)
        self.assertNotIn(".char-card-summary-grid", css_text)
        self.assertNotIn(".char-card-spotlight", css_text)
        self.assertNotIn(".char-card-officer-badge", css_text)
        self.assertNotIn(".char-card {", style_css_text)
        self.assertNotIn("body[data-route-family=\"character\"]::before {", style_css_text)
        self.assertNotIn("body[data-route-family=\"character\"] .char-card {", style_css_text)
        self.assertNotIn(".char-card-gear-shell .empty-slot {", style_css_text)
        self.assertIn("buildDossierIntelligencePanel({", runtime_text)
        self.assertIn("dashboardConfig: typeof config !== 'undefined' ? config : {}", runtime_text)
        self.assertIn("timelineEvents: typeof timelineData !== 'undefined' ? timelineData : []", runtime_text)


if __name__ == "__main__":
    unittest.main()
